;Build_Number:25.0.6895.4749.7953
[Main]
Name=Платформа nanoCAD x64
Version=25.0
MsiPath=nanoCAD.msi 
AdminNeed=0
ShowStartDialog=1 
ShowLangSelectDialog=0

[InstallProperties]
REGWIZARD_CHECKBOX=1
NANO360_CHECKBOX=1

[PreReq0]
Name=Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.6161
Url=http://www.microsoft.com/en-us/download/details.aspx?id=26368
InstPath=#Root#\PreReq\VcRedist2008_x64\vcredist_x64.exe
InstParams="#InstPath#" /Q
RegPath=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{5FCE6D76-F5DC-37AB-B2B8-22AB8CEDB1D4}\DisplayVersion
RegCond=VERSION>=9.0.30729.6161
ChooseDownload=vcredist_x64.exe
OSbit=2
Key64=1

[PreReq1]
Name=Microsoft Visual C++ 2012 Redistributable (x86) - 11.0.61030
Url=http://www.microsoft.com/en-us/download/details.aspx?id=30679
InstPath=#Root#\PreReq\VcRedist2012_x86\vcredist_x86.exe
InstParams="#InstPath#" /Q
RegPath=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{33d1fd90-4274-48a1-9bc1-97e33d9c2d6f}\DisplayVersion
RegCond=VERSION>=11.0.61030.0
RegPath0=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{B175520C-86A2-35A7-8619-86DC379688B9}\DisplayVersion
RegCond0=VERSION>=11.0.61030.0
ChooseDownload=VSU_4\vcredist_x86.exe

[PreReq2]
Name=Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.30501
Url=https://www.microsoft.com/en-US/download/details.aspx?id=40784
InstPath=#Root#\PreReq\VcRedist2013_x64\vcredist_x64.exe
InstParams="#InstPath#" /quiet
RegPath=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DevDiv\vc\Servicing\12.0\RuntimeMinimum\Version
RegCond=VERSION>=12.0.21005
OSbit=2
Key64=1

[PreReq3]
Name=Visual C++ Redistributable for Visual Studio 2015-2022 x64 - 14.32.31332.0
Url=https://support.microsoft.com/ru-ru/help/2977003/the-latest-supported-visual-c-downloads
InstPath=#Root#\PreReq\VcRedist2022_x64_32.31332.0\vc_redist.x64.exe
InstParams="#InstPath#" /install /quiet /norestart
RegPath=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DevDiv\VC\Servicing\14.0\RuntimeMinimum\Version
RegCond=VERSION>=14.32.31332
OSbit=2
Key64=1

[PreReq4]
Name=Visual C++ Redistributable for Visual Studio 2015-2022 x86 - 14.32.31332.0
Url=https://support.microsoft.com/ru-ru/help/2977003/the-latest-supported-visual-c-downloads
InstPath=#Root#\PreReq\VcRedist2022_x86_32.31332.0\vc_redist.x86.exe
InstParams="#InstPath#" /install /quiet /norestart
RegPath=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\DevDiv\VC\Servicing\14.0\RuntimeMinimum\Version
RegCond=VERSION>=14.32.31332
OSbit=0

[PreReq5]
Name=PostgreSQL 16.8
Url=https://repo.postgrespro.ru/win/64/PostgreSQL_16.8_64bit_Setup.exe
InstPath=#Root#\PreReq\PostgreSQL\PostgreSQL_16.8_64bit_Setup.exe
InstParams="#InstPath#" /S /init=pg_setup.ini
RegPath=HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Postgres Professional\X64\PostgreSQL\16\Installations\postgresql-16\Version
RegCond=VERSION>=16.8
RegPath0=HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\PostgresPro\X64\PostgresPro\16\Installations\postgresql-16\Version
RegCond0=VERSION>=16.8
RegPath1=HKEY_LOCAL_MACHINE\SOFTWARE\PostgreSQL\Installations\postgresql-x64-16\Version
RegCond1=VERSION>=16.8
Key64=1
PGCustomize=1
Optional=1

[PreReq6]
Name=NET Desktop Runtime 6.0.11
Url=https://download.visualstudio.microsoft.com/download/pr/0192a249-3ec8-4374-a827-e186dd58d55d/cec046575f3eb2247a10ba3d50f5cf6c/windowsdesktop-runtime-6.0.11-win-x64.exe
InstPath=#Root#\PreReq\Net6\windowsdesktop-runtime-6.0.11-win-x64.exe
InstParams="#InstPath#" /quiet /norestart
RegPath=HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.WindowsDesktop.App\LIST
RegCond=LIST>=6.0.11
OSbit=2
Key64=1

[PreReq7]
Name=PostgreSQL ODBC Driver 13.2 x64
Url=https://www.postgresql.org/ftp/odbc/versions/msi/
InstPath=#Root#\PreReq\psqlodbc_x64\psqlodbc_x64.msi
InstParams=msiexec /i "#InstPath#" /qn /quiet
RegPath=HKEY_LOCAL_MACHINE\SOFTWARE\psqlODBC_x64\Version
RegCond=VERSION>=13.02.0000
Key64=1

[DeploymentExcludeFolders]
Folder0=#Root#\LicServ

[DeploymentExcludeFiles]
File1=#Root#\htmlayout.dll
File2=#Root#\License.rtf
